// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace MusicDatabase.Models
{
    public partial class MusicContextModel
    {
        partial void Initialize()
        {
            var songEntry = SongEntryEntityType.Create(this);

            SongEntryEntityType.CreateAnnotations(songEntry);

            AddAnnotation("ProductVersion", "7.0.2");
        }
    }
}
