// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using MusicDatabase.Data;

#pragma warning disable 219, 612, 618
#nullable enable

namespace MusicDatabase.Models
{
    [DbContext(typeof(MusicContext))]
    public partial class MusicContextModel : RuntimeModel
    {
        static MusicContextModel()
        {
            var model = new MusicContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static MusicContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
